server:
  port: 9092
spring:
  application:
    name: lazurite-grove-plugin
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.251.128:8848