server:
  port: 9090
spring:
  application:
    name: lazurite-grove-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.251.128:3306/lazurite_grove?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: liukaiying1314
    druid:
      initialSize: 10
      minIdle: 1
      maxActive: 50
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          log-violation: true
          throw-exception: false
          config:
            delete-where-none-check: true
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
  redis:
    database: 0
    host: 192.168.251.128
    password: liukaiying1314
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.251.128:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.rurigokou.back.entity
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    com.rurigokou.back: DEBUG